export { default as Hero } from './Hero/Hero'
// export { default as LoginForm } from './LoginForm/LoginForm'
export { default as CreateQuestionary } from './CreateQuestionary/CreateQuestionary'
export { default as EditQuestionary } from './EditQuestionary/EditQuestionary'
export { default as Questionnaires } from './Questionnaires/Questionnaires'
export { default as Questionary } from './Questionary/Questionary'
export { default as MyResult } from './MyResult/MyResult'
